<a href="https://colab.research.google.com/github/HiveCase/DA4001-AI/blob/main/Assignments/Viva.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df = pd.DataFrame({
    "claim_id": [101, 102, 103, 104, 105, 106],
    "customer": ["A", "B", "A", "C", "B", "A"],
    "damage": ["dent", "scratch", "glass", "dent", "scratch", "dent"],
    "amount": [5000, 2000, 10000, 7000, 3000, 6000]
})

In [2]:
df

   claim_id customer   damage  amount
0       101        A     dent    5000
1       102        B  scratch    2000
2       103        A    glass   10000
3       104        C     dent    7000
4       105        B  scratch    3000
5       106        A     dent    6000

In [ ]:
df.groupby("customer",

In [ ]:
SELECT customer, SUM(amount) as total_amount FROM df Group by customer

In [ ]:
SELECT customer, SUM(amount) as total_amount
FROM df
Group by customer
order by total_amount desc limit 1

In [ ]:
3000-7000

In [7]:
def cate(amount):
  if amount<3000:
    return "low"
  elif (amount>=3000) & (amount <=7000):
    return "medium"
  else:
    return "high"

In [8]:
df["category"] = df['amount'].apply(cate)
df

   claim_id customer   damage  amount category
0       101        A     dent    5000   medium
1       102        B  scratch    2000      low
2       103        A    glass   10000     high
3       104        C     dent    7000   medium
4       105        B  scratch    3000   medium
5       106        A     dent    6000   medium